# Generated by Django 3.1.5 on 2021-05-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_posted',
            field=models.DateField(blank=True, help_text='m/d/Y'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='last_date',
            field=models.DateField(blank=True, help_text='m/d/Y'),
        ),
        migrations.AlterField(
            model_name='student_assign',
            name='date',
            field=models.DateField(blank=True, help_text='m/d/Y'),
        ),
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(blank=True, help_text='m/d/Y'),
        ),
    ]
