# Generated by Django 3.1.5 on 2021-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20210515_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(blank=True, help_text='m/d/Y'),
        ),
    ]
