# Generated by Django 3.1.5 on 2021-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='add_pdf',
            field=models.FileField(upload_to='syllabi/'),
        ),
    ]
