# Generated by Django 3.1.5 on 2021-02-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_pdf_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
