# Generated by Django 3.1.5 on 2021-05-25 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_pdf_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
