# Generated by Django 3.1.5 on 2021-01-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='name',
        ),
    ]
