# Generated by Django 3.1.5 on 2021-01-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210131_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
