# Generated by Django 3.1.5 on 2021-01-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20210131_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
