# Generated by Django 3.1.5 on 2021-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20210201_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
