# Generated by Django 3.1.5 on 2021-02-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210201_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
